services:
  api:
    container_name: api2
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/techchallenge-app
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/techchallenge-app
      - /usr/src/techchallenge-app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
