version: '4.0'
services:
  api:
    container_name: api2
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/techchallenge-app
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/techchallenge-app
      - /usr/src/techchallenge-app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    depends_on:
      - database-db
      - redis
    networks:
      - app-network

  database-db:
    image: 'bitnami/postgresql'
    container_name: database-db2
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=techchallenge
    ports:
      - 5434:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    container_name: redis2
    ports:
      - 6379:6379
    networks:
      - app-network

volumes:
  postgresql_data:
    driver: local

networks:
  app-network:
