apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-k8s
spec:
  selector:
    matchLabels:
      app: techchallenge-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: techchallenge-k8s
    spec:
      automountServiceAccountToken: false
      containers:
        - name: techchallenge-k8s
          image: viniciusdeliz/techchallenge-k8s:main
          ports: 
            - containerPort: 3001
          env:
            - name: ITEMS_SERVICE_HOST
              value: techchallenge-items-microservice
            - name: ITEMS_SERVICE_PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgresql://docker:dockerTech@postgres-db.clcbfwtduu8h.us-east-1.rds.amazonaws.com:5432/techchallenge?schema=public"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "8Gi"
