apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-k8s
spec:
  selector:
    matchLabels:
      app: techchallenge-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: techchallenge-k8s
    spec:
      automountServiceAccountToken: false
      containers:
        - name: techchallenge-k8s
          image: viniciusdeliz/techchallenge-k8s:latest
          ports: 
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              storage: "32Gi"
          env:
            - name: DATABASE_URL
              value: "postgresql://docker:docker@postgres:5432/techchallenge?schema=public"
          resources:
            requests:
              cpu: 1m
