apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-k8s
spec:
  selector:
    matchLabels:
      app: techchallenge-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: techchallenge-k8s
    spec:
      automountServiceAccountToken: false
      containers:
        - name: techchallenge-k8s
          image: viniciusdeliz/techchallenge-k8s:main
          ports: 
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "8Gi"
