apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-k8s
spec:
  selector:
    matchLabels:
      app: techchallenge-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: techchallenge-k8s
    spec:
      automountServiceAccountToken: false
      containers:
        - name: techchallenge-k8s
          image: viniciusdeliz/techchallenge-k8s:main
          ports: 
            - containerPort: 3001
          env:
            - name: ITEMS_SERVICE_HOST
              value: techchallenge-items-microservice
            - name: ITEMS_SERVICE_PORT
              value: "3000"
            - name: CHECKOUT_SERVICE_HOST
              value: techchallenge-checkout-microservice
            - name: CHECKOUT_SERVICE_PORT
              value: "3002"
            - name: ORDER_SERVICE_HOST
              value: techchallenge-orders-microservice
            - name: ORDER_SERVICE_PORT
              value: "3003"
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: DATABASE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "8Gi"
