name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install

    - name: Run Lint
      run: yarn run lint

    # - name: Run Tests
    #   run: yarn run test:cov
