name: Trigger Main Application Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build and Push Docker Image
    types:
      - completed
    branches:
      - main

jobs:
  trigger:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment in Terraform Repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.V_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/TechChallenge-BFHRV/k8s-app-infra-azure/dispatches \
            -d '{"event_type": "main-application-update", "client_payload": {"service_name": "main-application"}}'